### ISSUE TITLE
Add expected deposit receipts field to yaml files

### ISSUE THREAD

**Issue by s1na** [ewasm/scout#29]
EEs could output deposit receipts (via `eth2_pushNewDeposit` method). The expected receipt (if any) should be added to the YAML file to make it testable.

Related to #3

**Comment by poemm** [comment]
What exactly is a deposit receipt?

**Comment by s1na** [comment]
Sorry the issue description is not very clear. I'm here referring to the only other side-effects that an EE execution can have apart from the post state root. Deposit receipts are used by the EE to transfer BETH from their balance to a validator. E.g. in the `process_block` function of the [proposal 2](https://notes.ethereum.org/@vbuterin/Bkoaj4xpN?type=view):

```python
post_state, deposits = execute_code(exec_code, [pre_state, block.data])
```

After the shard block containing this deposit receipt is cross-linked into the beacon chain, it can be used in `process_new_validator`:

```python
def process_new_validator(state: BeaconState, new_validator: NewValidator) -> None:
    # Verify the receipt proof
    assert verify_deposit_receipt_proof(
        state,
        new_validator.receipt,
        new_validator.proof
    )
```
